# Dockerfile for Flask API
FROM python:3.8-slim

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

CMD ["python", "app.py"]


#Data Ingestion
#Data Preprocessing
#Model Training
#Model Prediction
#Model retraining
#Deploying using flask
#Deploying using streamlit
#Using Heroku - try
